build_dir: 13-open-magic-drc
build_id: '13'
commands:
- cp inputs/adk/magicrc .magicrc
- magic -noconsole -dnull run_drc.tcl | tee outputs/drc_results.log
edges_i:
  adk:
  - f: adk
    step: 0-analog-skywater-130nm
  design_merged.gds:
  - f: design_merged.gds
    step: 9-mentor-calibre-gdsmerge
edges_o: {}
inputs:
- adk
- design_merged.gds
name: open-magic-drc
outputs:
- drc_results.log
parameters:
  design_name: amplifier_self_bias
source: /home/users/lyt1314/SUMMER/dapnr/design/open-magic-drc
