#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-debug
#=========================================================================
# Generator : /home/users/lyt1314/Courses/ee372/aloe-sky130/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

export design_name=amplifier_self_bias

# Debug

calibre -rve -lvs svdb

