build_dir: 1-info
build_id: '1'
commands:
- echo "Design name      -- amplifier_self_bias"
- echo "Clock period     -- 10.0"
- echo "ADK              -- skywater-130nm-analog-adk"
- echo "ADK view         -- view-standard"
- echo
- echo "Constructed from -- /home/users/lyt1314/SUMMER/dapnr/design/construct.py"
- echo
edges_i: {}
edges_o: {}
name: info
parameters:
  adk: skywater-130nm-analog-adk
  adk_view: view-standard
  clock_period: 10.0
  construct_path: /home/users/lyt1314/SUMMER/dapnr/design/construct.py
  design_name: amplifier_self_bias
source: /home/users/lyt1314/Courses/ee372/aloe-sky130/mflowgen/steps/info
