#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /home/users/lyt1314/Courses/ee372/aloe-sky130/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export design_name=amplifier_self_bias
export clock_period=10.0
export construct_path=/home/users/lyt1314/SUMMER/dapnr/design/construct.py
export adk=skywater-130nm-analog-adk
export adk_view=view-standard

# Commands

echo "Design name      -- amplifier_self_bias"
echo "Clock period     -- 10.0"
echo "ADK              -- skywater-130nm-analog-adk"
echo "ADK view         -- view-standard"
echo
echo "Constructed from -- /home/users/lyt1314/SUMMER/dapnr/design/construct.py"
echo

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

