build_dir: 2-rtl
build_id: '2'
commands:
- cat amplifier_self_bias.v > outputs/design_rtl.v
edges_i: {}
edges_o:
  design_rtl.v:
  - f: design_rtl.v
    step: 3-dummy_dc
name: rtl
outputs:
- design_rtl.v
source: /home/users/lyt1314/SUMMER/dapnr/design/rtl
