build_dir: 11-netgen-lvs-def
build_id: '11'
commands:
- sh run_lvs.sh
edges_i:
  adk:
  - f: adk
    step: 0-analog-skywater-130nm
  design.lvs.v:
  - f: design.lvs.v
    step: 7-pointer
  design_extracted.spice:
  - f: design_extracted.spice
    step: 10-open-magic-def2spice
edges_o: {}
inputs:
- adk
- design_extracted.spice
- design.lvs.v
name: netgen-lvs-def
outputs:
- lvs_results.log
parameters:
  design_name: amplifier_self_bias
source: /home/users/lyt1314/SUMMER/dapnr/design/netgen-lvs-def
