build_dir: 10-open-magic-def2spice
build_id: '10'
commands:
- cp inputs/adk/magicrc .magicrc
- cp -L inputs/design.def.gz design.def.gz
- gunzip design.def.gz
- sed -i 's/\//____/g' design.def
- magic -noconsole -dnull extract.tcl | tee def2spice.log
edges_i:
  adk:
  - f: adk
    step: 0-analog-skywater-130nm
  design.def.gz:
  - f: design.def.gz
    step: 7-pointer
edges_o:
  design_extracted.spice:
  - f: design_extracted.spice
    step: 11-netgen-lvs-def
inputs:
- adk
- design.def.gz
name: open-magic-def2spice
outputs:
- design_extracted.spice
parameters:
  design_name: amplifier_self_bias
source: /home/users/lyt1314/SUMMER/dapnr/design/open-magic-def2spice
