name: post-sim

inputs:
  - adk
  # - design_merged.gds

outputs:
  - design_extracted_parasitic.spice

commands:
  - cp -a ../../interface/gen-0-id-42/bgr_top-merged.gds design_merged.gds
  - cp inputs/adk/magicrc .magicrc
  # extract with parasitics
  - magic -noconsole -dnull extract_parasitic.tcl | tee gds2spice.log
  - ln design_extracted_parasitic.spice outputs/design_extracted_parasitic.spice
  - python string_swap_parasitic.py
  # extract without parasitics
  - magic -noconsole -dnull extract.tcl | tee gds2spice.log
  - ln design_extracted.spice outputs/design_extracted.spice
  - python string_swap.py
  # post sim
  # - ngspice -c tf.sp -o tf-out.txt