build_dir: 14-open-magic-gds2spice
build_id: '14'
commands:
- cp inputs/adk/magicrc .magicrc
- magic -noconsole -dnull extract.tcl | tee gds2spice.log
- mv amplifier_self_bias.spice outputs/design_extracted.spice
- python string_swap.py
edges_i:
  adk:
  - f: adk
    step: 0-analog-skywater-130nm
  design_merged.gds:
  - f: design_merged.gds
    step: 9-mentor-calibre-gdsmerge
edges_o:
  design_extracted.spice:
  - f: design_extracted.spice
    step: 16-netgen-lvs-gds
  - f: design_extracted.spice
    step: 17-netgen-lvs-gds-device
  - f: design_extracted.spice
    step: 15-mentor-calibre-comparison
inputs:
- adk
- design_merged.gds
name: open-magic-gds2spice
outputs:
- design_extracted.spice
parameters:
  design_name: amplifier_self_bias
source: /home/users/lyt1314/SUMMER/dapnr/design/open-magic-gds2spice
