build_dir: 3-dummy_dc
build_id: '3'
commands:
- cat inputs/design_rtl.v > outputs/design.v
- cat inverter.sdc > outputs/design.sdc
edges_i:
  design_rtl.v:
  - f: design_rtl.v
    step: 2-rtl
edges_o:
  design.sdc:
  - f: design.sdc
    step: 5-cadence-innovus-flowsetup
  - f: design.sdc
    step: 6-cadence-innovus-init
  - f: design.sdc
    step: 8-aloe-PnR
  design.v:
  - f: design.v
    step: 5-cadence-innovus-flowsetup
  - f: design.v
    step: 6-cadence-innovus-init
  - f: design.v
    step: 8-aloe-PnR
inputs:
- design_rtl.v
name: dummy_dc
outputs:
- design.sdc
- design.v
source: /home/users/lyt1314/SUMMER/dapnr/design/dummy_dc
