#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /home/users/lyt1314/Courses/ee372/aloe-sky130/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export useful_skew=True
export order=netweight.tcl,pnr.tcl,interface.tcl,reporting.tcl
export cell_padding=2

# Commands

innovus -overwrite -64 -nowin -init start.tcl -cpus 8 -log logs/run.log
cd outputs
ln -sf ../checkpoints/design.checkpoint

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

