#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-debug
#=========================================================================
# Generator : /home/users/lyt1314/Courses/ee372/aloe-sky130/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

export useful_skew=True
export order=netweight.tcl,pnr.tcl,interface.tcl,reporting.tcl
export cell_padding=2

# Debug

innovus -overwrite -64 -init innovus-foundation-flow/custom-scripts/run-debug.tcl -log logs/debug.log

