#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-debug
#=========================================================================
# Generator : /home/users/lyt1314/Courses/ee372/aloe-sky130/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

export order=ini.tcl,floorplan.tcl,pin-assignments.tcl,tech.tcl,power.tcl,savefp.tcl,reporting.tcl

# Debug

innovus -overwrite -64
init innovus-foundation-flow/custom-scripts/run-debug.tcl
log logs/debug.log

