#! /usr/bin/env bash
set -euo pipefail
#=========================================================================
# mflowgen-run
#=========================================================================
# Generator : /home/users/lyt1314/Courses/ee372/aloe-sky130/mflowgen/mflowgen/core/build_orchestrator.py

# Pre

rm -f .time_end
date +%Y-%m%d-%H%M-%S > .time_start
MFLOWGEN_STEP_HOME=$PWD
export design_name=amplifier_self_bias

# Commands

ln -sf inputs/innovus-foundation-flow
cp -a ../../interface/gen-0-id-8/.  .
cd outputs
ln -sf ../checkpoints/design.checkpoint
ln -sf ../*.gds.gz            design.gds.gz
ln -sf ../*-merged.gds        design_merged.gds
ln -sf ../*.lvs.v             design.lvs.v
ln -sf ../*.lef               design.lef
ln -sf ../*.def.gz            design.def.gz

# Post

cd $MFLOWGEN_STEP_HOME
date +%Y-%m%d-%H%M-%S > .time_end

